version: "3"
services:
  redis:
    image: arm32v6/redis:5-alpine
    ports:
      - 6379:6379
  kinesis:
    build:
      context: kinesis
      dockerfile: Dockerfile-raspbian
    volumes:
      - /neochi/neochi-core/src/neochi:/code/neochi
    depends_on:
      - redis
